from sqlalchemy.orm import Session
from sqlalchemy import text
from models import Booking, BookingDetail, Room

def create_booking(db: Session, booking_data):
    # 1. Check room availability
    for room_id in booking_data.room_ids:
        available = db.execute(text("""
            SELECT 1 FROM room r
            WHERE r.id = :room_id
            AND NOT EXISTS (
                SELECT 1 FROM booking_detail bd
                JOIN booking b ON bd.booking_id = b.id
                WHERE bd.room_id = r.id
                AND b.status != 'cancelled'
                AND b.check_in_date < :co AND b.check_out_date > :ci
            )
        """), {"room_id": room_id, "co": booking_data.check_out_date, "ci": booking_data.check_in_date}).scalar()
        
        if not available:
            return None # A requested room is not available

    # 2. Create the main booking record
    num_guests = getattr(booking_data, 'number_of_guests', None)
    if num_guests is None:
        num_guests = 1

    new_booking = Booking(
        guest_id=booking_data.guest_id,
        check_in_date=booking_data.check_in_date,
        check_out_date=booking_data.check_out_date,
        status='pending',
        number_of_guests=num_guests
    )
    db.add(new_booking)
    db.flush() # Flush to get new_booking.id generated by DB

    # 3. Create booking details (rooms)
    details_res = []
    for room_id in booking_data.room_ids:
        # Fetch the room to get its base price from its type
        room = db.query(Room).filter(Room.id == room_id).first()
        price = room.room_type.base_price if room and room.room_type else 0
        
        detail = BookingDetail(
            booking_id=new_booking.id,
            room_id=room_id,
            price_per_night=price
        )
        db.add(detail)
        details_res.append(detail)

    # 4. Commit the transaction atomically
    try:
        db.commit()
        db.refresh(new_booking)
    except Exception as e:
        db.rollback()
        raise e

    # Build return payload
    return {
        "booking_id": new_booking.id, 
        "details": [{"booking_detail_id": d.id, "room_id": d.room_id} for d in details_res]
    }

def get_all_bookings(db: Session):
    bookings = db.query(Booking).all()
    result = []
    for booking in bookings:
        total_amount = float(sum(d.price_per_night for d in booking.details)) if booking.details else 0.0
        result.append({
            "id": booking.id,
            "guest_id": booking.guest_id,
            "guest_name": booking.guest.full_name if booking.guest else None,
            "check_in_date": booking.check_in_date,
            "check_out_date": booking.check_out_date,
            "status": booking.status,
            "number_of_guests": int(booking.number_of_guests) if booking.number_of_guests is not None else None,
            "total_price": total_amount,
            "total_amount": total_amount,
        })
    return result

def get_booking(db: Session, booking_id: int):
    booking = db.query(Booking).filter(Booking.id == booking_id).first()
    if not booking:
        return None
        
    result = {
        "id": booking.id,
        "guest_id": booking.guest_id,
        "guest_name": booking.guest.full_name if booking.guest else None,
        "check_in_date": booking.check_in_date,
        "check_out_date": booking.check_out_date,
        "status": booking.status,
        "number_of_guests": int(booking.number_of_guests) if booking.number_of_guests is not None else None,
        "total_price": float(sum(d.price_per_night for d in booking.details)) if booking.details else 0.0,
        "total_amount": float(sum(d.price_per_night for d in booking.details)) if booking.details else 0.0,
        "details": []
    }
    
    for detail in booking.details:
        result["details"].append({
            "id": detail.id,
            "room_id": detail.room_id,
            "price_per_night": float(detail.price_per_night),
            "room_number": detail.room.room_number if detail.room else None,
            "room_type": detail.room.room_type.name if detail.room and detail.room.room_type else None
        })
        
    return result

def update_status(db: Session, booking_id: int, status: str):
    booking = db.query(Booking).filter(Booking.id == booking_id).first()
    if not booking:
        return False
    booking.status = status
    db.commit()
    return True

def update_booking(db: Session, booking_id: int, booking_data):
    booking = db.query(Booking).filter(Booking.id == booking_id).first()
    if not booking:
        return False
    
    if 'guest_id' in booking_data: booking.guest_id = booking_data['guest_id']
    if 'check_in_date' in booking_data: booking.check_in_date = booking_data['check_in_date']
    if 'check_out_date' in booking_data: booking.check_out_date = booking_data['check_out_date']
    if 'status' in booking_data: booking.status = booking_data['status']
    if 'number_of_guests' in booking_data: booking.number_of_guests = booking_data['number_of_guests']
    
    db.commit()
    return True

def delete_booking(db: Session, booking_id: int):
    booking = db.query(Booking).filter(Booking.id == booking_id).first()
    if not booking:
        return False
    
    # Delete associated booking details first
    for detail in booking.details:
        db.delete(detail)
    
    db.delete(booking)
    db.commit()
    return True