"""Sync DB

Revision ID: 34bc41bf8ffb
Revises: 
Create Date: 2026-04-25 22:37:06.775771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34bc41bf8ffb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_booking_guest'), table_name='booking')
    op.create_index(op.f('ix_booking_guest_id'), 'booking', ['guest_id'], unique=False)
    op.create_index(op.f('ix_booking_id'), 'booking', ['id'], unique=False)
    op.drop_constraint(op.f('booking_ibfk_1'), 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'guest', ['guest_id'], ['id'])
    op.drop_column('booking', 'created_at')
    op.drop_column('booking', 'updated_at')
    op.alter_column('booking_detail', 'booking_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('booking_detail', 'room_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_booking_detail_booking'), table_name='booking_detail')
    op.create_index(op.f('ix_booking_detail_id'), 'booking_detail', ['id'], unique=False)
    op.drop_constraint(op.f('booking_detail_ibfk_2'), 'booking_detail', type_='foreignkey')
    op.drop_constraint(op.f('booking_detail_ibfk_1'), 'booking_detail', type_='foreignkey')
    op.create_foreign_key(None, 'booking_detail', 'booking', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'booking_detail', 'room', ['room_id'], ['id'])
    op.drop_column('booking_detail', 'created_at')
    op.drop_column('booking_detail', 'updated_at')
    op.alter_column('booking_service', 'booking_detail_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('booking_service', 'service_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('booking_service', 'employee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('booking_service', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('idx_booking_service_detail'), table_name='booking_service')
    op.create_index(op.f('ix_booking_service_id'), 'booking_service', ['id'], unique=False)
    op.drop_constraint(op.f('booking_service_ibfk_3'), 'booking_service', type_='foreignkey')
    op.drop_constraint(op.f('booking_service_ibfk_1'), 'booking_service', type_='foreignkey')
    op.drop_constraint(op.f('booking_service_ibfk_2'), 'booking_service', type_='foreignkey')
    op.create_foreign_key(None, 'booking_service', 'booking_detail', ['booking_detail_id'], ['id'])
    op.create_foreign_key(None, 'booking_service', 'service', ['service_id'], ['id'])
    op.create_foreign_key(None, 'booking_service', 'employee', ['employee_id'], ['id'])
    op.drop_column('booking_service', 'created_at')
    op.add_column('employee', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('employee', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('employee', sa.Column('role', sa.String(length=20), nullable=True))
    op.alter_column('employee', 'full_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('employee', 'position',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_index(op.f('ix_employee_username'), 'employee', ['username'], unique=True)
    op.drop_column('employee', 'created_at')
    op.drop_column('employee', 'updated_at')
    op.alter_column('guest', 'full_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('guest', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('guest', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
    op.drop_index(op.f('email'), table_name='guest')
    op.create_index(op.f('ix_guest_email'), 'guest', ['email'], unique=True)
    op.create_index(op.f('ix_guest_id'), 'guest', ['id'], unique=False)
    op.drop_column('guest', 'created_at')
    op.drop_column('guest', 'updated_at')
    op.alter_column('payment', 'booking_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('payment', 'payment_method',
               existing_type=mysql.ENUM('cash', 'credit_card', 'bank_transfer', 'other', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('payment', 'payment_date',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_payment_booking'), table_name='payment')
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.drop_constraint(op.f('payment_ibfk_1'), 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'booking', ['booking_id'], ['id'])
    op.alter_column('room', 'room_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('room', 'room_type_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('room', 'status',
               existing_type=mysql.ENUM('available', 'occupied', 'needs_cleaning', 'maintenance', 'reserved', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'available'"))
    op.drop_index(op.f('idx_room_status'), table_name='room')
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.drop_constraint(op.f('room_ibfk_1'), 'room', type_='foreignkey')
    op.create_foreign_key(None, 'room', 'room_type', ['room_type_id'], ['id'])
    op.drop_column('room', 'created_at')
    op.drop_column('room', 'updated_at')
    op.create_index(op.f('ix_room_type_id'), 'room_type', ['id'], unique=False)
    op.drop_column('room_type', 'created_at')
    op.drop_column('room_type', 'updated_at')
    op.alter_column('service', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('service', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.alter_column('service', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('service', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('room_type', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('room_type', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index(op.f('ix_room_type_id'), table_name='room_type')
    op.add_column('room', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('room', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.create_foreign_key(op.f('room_ibfk_1'), 'room', 'room_type', ['room_type_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.create_index(op.f('idx_room_status'), 'room', ['status'], unique=False)
    op.alter_column('room', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('available', 'occupied', 'needs_cleaning', 'maintenance', 'reserved', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'available'"))
    op.alter_column('room', 'room_type_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('room', 'room_number',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=False)
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key(op.f('payment_ibfk_1'), 'payment', 'booking', ['booking_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.create_index(op.f('idx_payment_booking'), 'payment', ['booking_id'], unique=False)
    op.alter_column('payment', 'payment_date',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('payment', 'payment_method',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('cash', 'credit_card', 'bank_transfer', 'other', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('payment', 'booking_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('guest', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('guest', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index(op.f('ix_guest_id'), table_name='guest')
    op.drop_index(op.f('ix_guest_email'), table_name='guest')
    op.create_index(op.f('email'), 'guest', ['email'], unique=True)
    op.alter_column('guest', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
    op.alter_column('guest', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('guest', 'full_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               existing_nullable=False)
    op.add_column('employee', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('employee', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index(op.f('ix_employee_username'), table_name='employee')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.alter_column('employee', 'position',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('employee', 'full_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               existing_nullable=False)
    op.drop_column('employee', 'role')
    op.drop_column('employee', 'hashed_password')
    op.drop_column('employee', 'username')
    op.add_column('booking_service', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(None, 'booking_service', type_='foreignkey')
    op.drop_constraint(None, 'booking_service', type_='foreignkey')
    op.drop_constraint(None, 'booking_service', type_='foreignkey')
    op.create_foreign_key(op.f('booking_service_ibfk_2'), 'booking_service', 'service', ['service_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('booking_service_ibfk_1'), 'booking_service', 'booking_detail', ['booking_detail_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('booking_service_ibfk_3'), 'booking_service', 'employee', ['employee_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_booking_service_id'), table_name='booking_service')
    op.create_index(op.f('idx_booking_service_detail'), 'booking_service', ['booking_detail_id'], unique=False)
    op.alter_column('booking_service', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('booking_service', 'employee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('booking_service', 'service_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('booking_service', 'booking_detail_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('booking_detail', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('booking_detail', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(None, 'booking_detail', type_='foreignkey')
    op.drop_constraint(None, 'booking_detail', type_='foreignkey')
    op.create_foreign_key(op.f('booking_detail_ibfk_1'), 'booking_detail', 'booking', ['booking_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('booking_detail_ibfk_2'), 'booking_detail', 'room', ['room_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_booking_detail_id'), table_name='booking_detail')
    op.create_index(op.f('idx_booking_detail_booking'), 'booking_detail', ['booking_id'], unique=False)
    op.alter_column('booking_detail', 'room_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('booking_detail', 'booking_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('booking', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('booking', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(op.f('booking_ibfk_1'), 'booking', 'guest', ['guest_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_booking_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_guest_id'), table_name='booking')
    op.create_index(op.f('idx_booking_guest'), 'booking', ['guest_id'], unique=False)
    # ### end Alembic commands ###
